name: CustomWhois
main: mn.frd.CustomWhois.CustomWhois
version: 1.2.1

commands:
  whois:
    description: Display informations about a specific player
    usage: /<command>
permissions:
  customwhois.whois.self:
    default: true
  customwhois.whois.others:
    default: op
  customwhois.custom.nick:
    default: false
  customwhois.custom.health:
    default: false
  customwhois.custom.hunger:
    default: false
  customwhois.custom.exp:
    default: false
  customwhois.custom.location:
    default: false
  customwhois.custom.money:
    default: false
  customwhois.custom.ip:
    default: false
  customwhois.custom.gamemode:
    default: false
  customwhois.custom.godmode:
    default: false
  customwhois.custom.op:
    default: false
  customwhois.custom.flying:
    default: false
  customwhois.custom.afk:
    default: false
  customwhois.custom.jailed:
    default: false
  customwhois.custom.muted:
    default: false
