name: CustomWhois
main: mn.frd.CustomWhois.CustomWhois
version: 1.0

commands: 
  whois:
    description: Display informations about a specific player
    usage: /<command>
permissions:
  customwhois.whois.self:
    default: true
  customwhois.whois.others:
    default: op